// src/contexts/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect } from 'react';

// Language constants
export const LANGUAGES = {
    ENGLISH: 'en',
    HEBREW: 'he'
};

// Translations object - COMPLETE WITH ALL YOUR EXISTING and NEW TRANSLATIONS
const translations = {
    en: {
        // Navigation
        'nav.dashboard': 'Dashboard',
        'nav.eventManagement': 'Event Management',
        'nav.userManagement': 'User Management',
        'nav.forms': 'Forms',
        'nav.backupSync': 'Backup/Sync',
        'nav.importExport': 'Import/Export Data',
        'nav.gallery': 'Gallery',
        'nav.myAccount': 'My Account',
        'nav.signOut': 'Sign Out',
        'nav.logo': 'ParaGrutaRally',
        'nav.events': 'Events',
        'nav.users': 'Users',
        'nav.kids': 'Kids',
        'nav.teams': 'Teams',
        'nav.vehicles': 'Vehicles',

        // Dashboard
        'dashboard.title': 'Admin Dashboard',
        'dashboard.totalUsers': 'Total Users',
        'dashboard.upcomingEvents': 'Upcoming Events',
        'dashboard.totalKids': 'Total Kids',
        'dashboard.activeTeams': 'Active Teams',
        'dashboard.recentActivities': 'Recent Activities',
        'dashboard.newUser': 'New user',
        'dashboard.wasAdded': 'was added',
        'dashboard.event': 'Event',
        'dashboard.wasCreated': 'was created',
        'dashboard.newPhotos': 'new photos',
        'dashboard.wereAdded': 'were added to the gallery',
        'dashboard.racingReady': 'Racing Ready',
        'dashboard.racingVehicles': 'Racing Vehicles',
        'dashboard.available': 'Available',
        'dashboard.systemUsers': 'System Users',
        'dashboard.autoRefresh': 'Dashboard updates automatically every 5 minutes',
        'dashboard.teamCreated': 'Team <strong>{teamName}</strong> was created.',
        'dashboard.justNow': 'Just now',
        'dashboard.minutesAgo': '{count} minute{plural} ago',
        'dashboard.hoursAgo': '{count} hour{plural} ago',
        'dashboard.daysAgo': '{count} day{plural} ago',

        // Event Management
        'events.title': 'Event Management',
        'events.createNew': 'Create New Event',
        'events.searchPlaceholder': 'Search events...',
        'events.search': 'Search',
        'events.allEvents': 'All Events',
        'events.upcoming': 'Upcoming Events',
        'events.completed': 'Completed Events',
        'events.allLocations': 'All Locations',
        'events.jerusalem': 'Jerusalem',
        'events.telAviv': 'Tel Aviv',
        'events.haifa': 'Haifa',
        'events.eilat': 'Eilat',
        'events.eventName': 'Event Name',
        'events.date': 'Date',
        'events.location': 'Location',
        'events.participants': 'Participants',
        'events.status': 'Status',
        'events.actions': 'Actions',
        'events.edit': 'Edit',
        'events.view': 'View',
        'events.delete': 'Delete',
        'events.loading': 'Loading events...',
        'events.noEvents': 'No events found',
        'events.previous': 'Previous',
        'events.next': 'Next',
        'events.addNewEvent': 'Add New Event',
        'events.exportEvents': 'Export Events',
        'events.totalEvents': 'Total Events',
        'events.completedEvents': 'Completed Events',
        'events.eventInfo': 'Event Info',
        'events.eventsLowercase': 'events',
        'events.showing': 'Showing',
        'events.searchLabel': 'Search',
        'events.unnamedEvent': 'Unnamed Event',
        'events.noDescription': 'No description available',
        'events.locationTBD': 'Location TBD',
        'events.dateTBD': 'Date TBD',
        'events.fetchError': 'Failed to load events. Please try again.',
        'events.noGalleryFolder': 'This event does not have a gallery folder.',
        'events.deleteSuccess': 'Event "{eventName}" deleted successfully',
        'events.includingGallery': 'including gallery photos',
        'events.deleteFailed': 'Failed to delete event: {error}',
        'events.deleteError': 'Failed to delete event. Please try again.',
        'events.noEventsCreated': 'No events have been created yet. Start by creating your first event!',
        'events.createFirstEvent': 'Create First Event',
        'events.createNewEvent': 'Create New Event',
        'events.hasGallery': 'Has Gallery',
        'events.viewDetails': 'View Details',
        'events.editEvent': 'Edit Event',
        'events.viewGallery': 'View Gallery',
        'events.deleteEvent': 'Delete Event',
        'events.description': 'Description',
        'events.notes': 'Notes',
        'events.participatingTeams': 'Participating Teams',
        'events.teamsRegistered': '{count} teams registered',
        'events.gallery': 'Gallery',
        'events.deleteConfirmTitle': 'Are you sure you want to delete this event?',
        'events.deleteConfirmMessage': 'You are about to delete "{eventName}". This action cannot be undone.',
        'events.deletionSummaryTitle': 'The following will be permanently deleted:',
        'events.eventInformation': 'Event information and details',
        'events.eventCoverImage': 'Event cover image',
        'events.allGalleryPhotos': 'All photos in the event gallery',
        'events.galleryFolderDetected': 'Gallery Folder Detected',
        'events.galleryFolderQuestion': 'This event has an associated photo gallery. What would you like to do with the photos?',
        'events.keepGalleryPhotos': 'Keep Gallery Photos',
        'events.keepGalleryDescription': 'Delete only the event, preserve all photos in the gallery',
        'events.deleteGalleryToo': 'Delete Gallery Too',
        'events.deleteGalleryDescription': 'Delete the event AND permanently remove all photos from the gallery',
        'events.deleting': 'Deleting...',
        'events.deleteEventAndGallery': 'Delete Event & Gallery',
        'events.deleteEventOnly': 'Delete Event Only',
        'events.upcomingEvents': 'Upcoming Events',
        'events.timeTBD': 'Time TBD',
        'events.addressTBD': 'Address TBD',
        'events.organizerTBD': 'TBD',
        'events.eventNotFound': 'Event not found',
        'events.loadError': 'Failed to load event. Please try again.',
        'events.loadingEvent': 'Loading event...',
        'events.backToEvents': 'Back to Events',
        'events.racingEventDetails': 'Racing Event Details!',
        'events.eventInformationSubtitle': 'Event information and details',
        'events.eventDetails': 'Event Details',
        'events.time': 'Time',
        'events.organizer': 'Organizer',
        'events.fullAddress': 'Full Address',
        'events.additionalNotes': 'Additional Notes',
        'events.loadingTeamData': 'Loading team data...',
        'events.unknownTeam': 'Unknown Team',
        'events.leader': 'Leader',
        'events.kidsInTeam': 'Kids in team',
        'events.eventGallery': 'Event Gallery',
        'events.eventAlbum': '{eventName} Album',
        'events.viewManagePhotos': 'View and manage photos from this event',
        'events.cancelled': 'Cancelled',
        'events.editRacingEvent': 'Edit Racing Event',
        'events.loadingEventData': 'Loading event data...',
        'events.racingEvent': 'Racing Event',
        'events.racingEventDescription': 'Competitive racing event with winners',
        'events.newFamiliesEvent': 'New Families Event',
        'events.newFamiliesEventDescription': 'Welcome new families with a fun racing day',
        'events.socialEvent': 'Social Event',
        'events.socialEventDescription': 'Community gathering and activities',
        'events.basicInformation': 'Basic Information',
        'events.eventNamePlaceholder': 'e.g., Summer Racing Championship 2025',
        'events.requiredField': '*Required field',
        'events.eventType': 'Event Type',
        'events.descriptionPlaceholder': 'Describe your racing event in detail...',
        'events.organizerPlaceholder': 'Event organizer name',
        'events.dateAndTime': 'Date & Time',
        'events.eventDate': 'Event Date',
        'events.eventTime': 'Event Time',
        'events.futureDateTime': '*Event date and time must be in the future',
        'events.locationDetails': 'Location Details',
        'events.locationName': 'Location Name',
        'events.locationPlaceholder': 'e.g., Jerusalem Racing Park',
        'events.addressPlaceholder': 'Complete address of the event',
        'events.teamsAssigned': '{count} team{plural} assigned',
        'events.addTeams': 'Add Teams',
        'events.removeTeam': 'Remove team',
        'events.noTeamsAssigned': 'No teams assigned to this event yet.',
        'events.addTeamsHint': 'Click "Add Teams" to assign teams to participate.',
        'events.eventImage': 'Event Image',
        'events.eventImageOptional': 'Event Image (Optional)',
        'events.clickToUpload': 'Click to upload event image',
        'events.imageRecommendation': 'Recommended: 1200x600px, JPG or PNG',
        'events.cancelNewImage': 'Cancel New Image',
        'events.clickToChange': 'Click to change image',
        'events.additionalDetails': 'Additional Details',
        'events.notesOptional': 'Notes (Optional)',
        'events.notesPlaceholder': 'Additional notes about the event...',
        'events.updateEvent': 'Update Event',
        'events.uploadingImage': 'Uploading Image...',
        'events.updatingEvent': 'Updating Event...',
        'events.imageUploadWarning': 'Warning: Failed to upload new image, but event will be updated with other changes.',
        'events.additionalNotesDefault': 'Additional notes about the event',
        'events.updateSuccess': 'Event updated successfully!',
        'events.updateError': 'Error updating event: {error}',

        // User Management
        'users.title': 'User Management',
        'users.manage': 'Manage Users',
        'users.description': 'This page will contain user management functionality including:',
        'users.viewAll': 'View all users',
        'users.addNew': 'Add new users',
        'users.editProfiles': 'Edit user profiles',
        'users.manageRoles': 'Manage user roles',
        'users.permissions': 'User permissions',
        'users.addNewUser': 'Add New User',
        'users.exportUsers': 'Export Users',
        'users.createNewUser': 'Create New User',
        'users.totalUsers': 'Total Users',
        'users.admins': 'Admins',
        'users.instructors': 'Instructors',
        'users.parents': 'Parents',
        'users.admin': 'Admin',
        'users.instructor': 'Instructor',
        'users.parent': 'Parent',
        'users.host': 'Host',
        'users.searchPlaceholder': 'Search users by name or email...',
        'users.filterByRole': 'Filter by Role',
        'users.allRoles': 'All Roles',
        'users.clearFilters': 'Clear Filters',
        'users.showing': 'Showing',
        'users.usersLowercase': 'users',
        'users.filteredBy': 'Filtered by',
        'users.searching': 'Searching',
        'users.loadingUsers': 'Loading users...',
        'users.noUsersFound': 'No users found',
        'users.createFirstUser': 'Start by creating your first user.',
        'users.searchInUsers': 'Search in users',
        'users.clearSearch': 'Clear search',
        'users.searchResults': '{count} of {total} users',
        'users.totalUsersCount': '{count} users total',
        'users.sortByDisplayName': 'Click to sort by Display Name',
        'users.sortByFullName': 'Click to sort by Full Name',
        'users.sortByEmail': 'Click to sort by Email',
        'users.sortByPhone': 'Click to sort by Phone',
        'users.sortByRole': 'Click to sort by Role',
        'users.sortByCreatedDate': 'Click to sort by Created Date',
        'users.sortByLastLogin': 'Click to sort by Last Login',
        'users.displayName': 'Display Name',
        'users.fullName': 'Full Name',
        'users.email': 'Email',
        'users.phone': 'Phone',
        'users.role': 'Role',
        'users.createdAt': 'Created At',
        'users.lastLogin': 'Last Login',
        'users.actions': 'Actions',
        'users.updateUser': 'Update user',
        'users.update': 'Update',
        'users.noSearchResults': 'No users match your search: "{searchTerm}"',
        'users.clearSearchButton': 'Clear Search',
        'users.displayNameRequired': 'Display name is required',
        'users.nameRequired': 'Name is required',
        'users.phoneRequired': 'Phone number is required',
        'users.roleRequired': 'Role is required',
        'users.updateError': 'Failed to update user. Please try again.',
        'users.displayNamePlaceholder': 'Enter display name',
        'users.emailAddress': 'Email Address',
        'users.emailCannotChange': 'Email cannot be changed',
        'users.emailLinkedToAuth': 'Email cannot be changed as it\'s linked to authentication',
        'users.fullNamePlaceholder': 'Enter full name',
        'users.phoneNumber': 'Phone Number',
        'users.phoneNumberPlaceholder': 'Enter phone number',
        'users.updating': 'Updating...',
        'users.updateUserButton': 'Update User',


        // My Account
        'account.title': 'My Account',
        'account.profile': 'Profile Information',
        'account.security': 'Security Settings',
        'account.preferences': 'Preferences',
        'account.editProfile': 'Edit Profile',
        'account.fullName': 'Full Name',
        'account.email': 'Email Address',
        'account.phone': 'Phone Number',
        'account.organization': 'Organization',
        'account.bio': 'Bio',
        'account.saveChanges': 'Save Changes',
        'account.cancel': 'Cancel',

        // Forms
        'forms.title': 'Forms Management',
        'forms.manage': 'Manage Forms',
        'forms.description': 'This page will contain form management functionality including:',
        'forms.createNew': 'Create new forms',
        'forms.editExisting': 'Edit existing forms',
        'forms.viewSubmissions': 'View form submissions',
        'forms.templates': 'Form templates',
        'forms.analytics': 'Form analytics',
        'forms.createNewForm': 'Create New Form',
        'forms.viewTemplates': 'View Templates',

        // Backup/Sync
        'backup.title': 'Backup & Sync',
        'backup.databaseBackup': 'Database Backup',
        'backup.description': 'Create and manage backups of your application data.',
        'backup.createNew': 'Create New Backup',
        'backup.viewHistory': 'View Backup History',
        'backup.recentBackups': 'Recent Backups',
        'backup.noBackups': 'No backups created yet. Click "Create New Backup" to get started.',
        'backup.cloudSync': 'Cloud Sync Settings',
        'backup.configurSync': 'Configure synchronization with cloud storage services.',
        'backup.googleDrive': 'Google Drive',
        'backup.dropbox': 'Dropbox',
        'backup.status': 'Status',
        'backup.notConnected': 'Not Connected',
        'backup.connect': 'Connect',
        'backup.automatedSchedule': 'Automated Backup Schedule',
        'backup.setSchedule': 'Set up automated backups on a regular schedule.',
        'backup.daily': 'Daily',
        'backup.weekly': 'Weekly',
        'backup.monthly': 'Monthly',
        'backup.custom': 'Custom',
        'backup.saveSettings': 'Save Settings',

        // Import/Export
        'import.title': 'Import/Export Data',
        'import.importData': 'Import Data',
        'import.importDescription': 'Upload data files to import information into the system.',
        'import.selectDataType': 'Select Data Type to Import:',
        'import.selectFile': 'Select File (CSV or Excel):',
        'import.users': 'Users',
        'import.kids': 'Kids',
        'import.teams': 'Teams',
        'import.events': 'Events',
        'import.selectedFile': 'Selected file:',
        'import.size': 'Size:',
        'import.overwriteRecords': 'Overwrite existing records',
        'import.skipHeader': 'Skip header row',
        'import.importButton': 'Import Data',
        'import.exportData': 'Export Data',
        'import.exportDescription': 'Download data from the system as CSV or Excel files.',
        'import.selectExportType': 'Select Data Type to Export:',
        'import.allData': 'All Data',
        'import.exportFormat': 'Export Format:',
        'import.csv': 'CSV',
        'import.excel': 'Excel',
        'import.includeHeaders': 'Include header row',
        'import.includeTimestamp': 'Include timestamp in filename',
        'import.exportButton': 'Export Data',
        'import.recentActivity': 'Recent Activity',

        // Gallery
        'gallery.title': 'Gallery',
        'gallery.allPhotos': 'All Photos',
        'gallery.events': 'Events',
        'gallery.races': 'Races',
        'gallery.teams': 'Teams',
        'gallery.awards': 'Award Ceremonies',
        'gallery.uploadPhotos': 'Upload Photos',
        'gallery.noPhotos': 'No photos found in this album.',

        // Teams Management - NEW TRANSLATIONS
        'teams.title': 'Teams Management',
        'teams.addNewTeam': 'Add New Team',
        'teams.refresh': 'Refresh',
        'teams.exportTeams': 'Export Teams',
        'teams.totalTeams': 'Total Teams',
        'teams.activeTeams': 'Active Teams',
        'teams.teamsWithoutKids': 'Teams without Kids',
        'teams.teamsWithKids': 'Teams with Kids',
        'teams.searchPlaceholder': 'Search by team name or instructor...',
        'teams.clearAll': 'Clear All',
        'teams.showing': 'Showing',
        'teams.of': 'of',
        'teams.teams': 'teams',
        'teams.priorityFilter': 'PRIORITY: Teams without kids',
        'teams.status': 'Status',
        'teams.capacity': 'Capacity',
        'teams.allStatus': 'All Status',
        'teams.active': 'Active',
        'teams.inactive': 'Inactive',
        'teams.allTeams': 'All Teams',
        'teams.emptyTeams': 'Empty Teams',
        'teams.availableSpots': 'Available Spots',
        'teams.fullTeams': 'Full Teams',
        'teams.teamInfo': 'Team Info',
        'teams.instructor': 'Instructor',
        'teams.members': 'Members',
        'teams.actions': 'Actions',
        'teams.noInstructor': 'No Instructor',
        'teams.loadingTeams': 'Loading teams...',
        'teams.noTeamsFound': 'No teams found',
        'teams.adjustFilters': 'Try adjusting your search or filters',
        'teams.addFirstTeam': 'Add First Team',
        'teams.reset': 'Reset',
        'teams.permissionError': 'Permission Error',
        'teams.reloadPage': 'Reload Page',
        'teams.tryAgain': 'Try Again',
        'teams.deleteConfirm': 'Are you sure you want to delete {teamName}? This action cannot be undone.',
        'teams.cannotDelete': 'Cannot delete {teamName} because it has {memberCount} members. Please move the kids to other teams first.',
        'teams.deleteSuccess': '{teamName} has been deleted successfully!',
        'teams.deleteFailed': 'Failed to delete team. Please try again.',
        'teams.onlyAdminsCanDelete': 'Only administrators can delete teams.',
        'teams.viewDetails': 'View Details',
        'teams.editTeam': 'Edit Team',
        'teams.deleteTeam': 'Delete Team',
        'teams.unlimited': 'Unlimited',
        'teams.hasInstructor': 'Has Instructor',
        'teams.membersCount': '{current}/{max}',
        'teams.empty': 'Empty',
        'teams.available': 'Available',
        'teams.full': 'Full',
        'teams.unnamedTeam': 'Unnamed Team',
        'teams.loadError': 'Failed to load teams',
        'teams.editFunctionality': 'Edit functionality for {teamName} would go here.',
        'teams.updateRacingTeam': 'Update Racing Team!',
        'teams.loadingTeamData': 'Loading team data...',
        'teams.teamNotFound': 'Team not found!',
        'teams.loadDataError': 'Failed to load team data. Please try again.',
        'teams.updateSuccess': '🏁 Team "{teamName}" has been updated successfully! 🏎️',
        'teams.updateError': 'Failed to update team. Please try again.',
        'teams.viewingCurrentInfo': 'You\'re viewing Team {teamName}\'s current information. Make changes below to update! 🏎️',
        'teams.backToTeams': 'Back to Teams',
        'teams.teamIdentity': '🏎️ Team Identity',
        'teams.racingInstructors': '👨‍🏫 Racing Instructors',
        'teams.teamRacers': '🏎️ Team Racers ({current}/{max})',
        'teams.teamNotes': '📝 Team Notes',
        'teams.teamName': 'Team Name',
        'teams.teamNamePlaceholder': 'Thunder Racers, Speed Demons, Lightning Bolts...',
        'teams.maxRacers': 'Max Racers',
        'teams.teamDescription': 'Team Description',
        'teams.teamDescriptionPlaceholder': 'What makes this team special? Their racing spirit, teamwork, or special skills...',
        'teams.teamStatus': 'Team Status',
        'teams.activeReady': '✅ Active & Ready to Race',
        'teams.inactivePrep': '⏸️ Inactive (Prep Mode)',
        'teams.focusIndicator': '← Update Here!',
        'teams.noInstructorsAvailable': 'No instructors available. Add some instructors first!',
        'teams.teamLeader': 'Team Leader',
        'teams.chooseTeamLeader': '🎯 Choose Team Leader',
        'teams.leaderOption': '👑 {instructorName}',
        'teams.capacityWarning': 'Capacity Warning',
        'teams.noKidsAvailable': 'No kids available for assignment! 🎉',
        'teams.allKidsAssigned': 'All kids are already assigned to teams.',
        'teams.currentlyInOtherTeam': '📍 Currently in other team',
        'teams.nameRequired': 'Team name is required',
        'teams.capacityRange': 'Max capacity must be between 1 and 50',
        'teams.tooManyKids': 'Cannot assign more kids ({current}) than max capacity ({max})',
        'teams.specialNotesStrategy': '📝 Special Notes & Strategy',
        'teams.notesPlaceholder': 'Team strategy, special requirements, or any other important notes...',
        'teams.updatingTeam': 'Updating Team...',
        'teams.saveUpdates': 'Save Updates! 🏁',
        'teams.noChangesToSave': 'No Changes to Save',


        // Kids Management - NEW TRANSLATIONS
        'kids.title': 'Kids Management',
        'kids.addNewKid': 'Add New Kid',
        'kids.refresh': 'Refresh',
        'kids.exportKids': 'Export Kids',
        'kids.kidsWithoutTeams': 'Kids without Teams',
        'kids.totalKids': 'Total Kids',
        'kids.yourKids': 'Your Kids',
        'kids.activeKids': 'Active Kids',
        'kids.kidsWithTeams': 'Kids with Teams',
        'kids.searchPlaceholder': 'Search by kid name or parent name...',
        'kids.clearAll': 'Clear All',
        'kids.showing': 'Showing',
        'kids.of': 'of',
        'kids.kids': 'kids',
        'kids.priorityFilter': 'PRIORITY: Kids without teams',
        'kids.teamStatus': 'Team Status',
        'kids.allKids': 'All Kids',
        'kids.noTeam': 'No Team',
        'kids.withTeam': 'With Team',
        'kids.allStatus': 'All Status',
        'kids.pending': 'Pending',
        'kids.completed': 'Completed',
        'kids.cancelled': 'Cancelled',
        'kids.active': 'Active',
        'kids.kidInfo': 'Kid Info',
        'kids.photo': 'Photo',
        'kids.age': 'Age',
        'kids.team': 'Team',
        'kids.status': 'Status',
        'kids.actions': 'Actions',
        'kids.loadingKids': 'Loading kids...',
        'kids.noKidsFound': 'No kids found',
        'kids.noKidsRegistered': 'No kids registered under your account',
        'kids.adjustFilters': 'Try adjusting your search or filters',
        'kids.addFirstKid': 'Add First Kid',
        'kids.assignTeam': 'Assign Team',
        'kids.changeTeam': 'Change Team',
        'kids.deleteConfirm': 'Are you sure you want to delete {kidName}? This action cannot be undone.',
        'kids.deleteSuccess': '{kidName} has been deleted successfully!',
        'kids.deleteFailed': 'Failed to delete kid. Please try again.',
        'kids.onlyAdminsCanDelete': 'Only administrators can delete kids.',
        'kids.teamChanged': '{kidName} has been {action} {teamName}',
        'kids.assignedTo': 'assigned to',
        'kids.removedFrom': 'removed from team',
        'kids.updated': '{kidName} has been updated successfully!',
        'kids.name': 'Name',
        'kids.parentName': 'Parent',
        'kids.participantNumber': 'Participant #',
        'kids.viewDetails': 'View Details',
        'kids.editKid': 'Edit Kid',
        'kids.deleteKid': 'Delete Kid',
        'kids.clickToView': 'Click to view details',
        'kids.reset': 'Reset',
        'kids.permissionError': 'Permission Error',
        'kids.reloadPage': 'Reload Page',
        'kids.tryAgain': 'Try Again',
        'kids.loadingPermissions': 'Loading permissions...',

        // Export functionality - NEW TRANSLATIONS
        'export.title': 'Export Data',
        'export.description': 'Download data as Excel or CSV files',
        'export.selectFormat': 'Select Format',
        'export.excel': 'Excel (XLSX)',
        'export.csv': 'CSV',
        'export.includeHeaders': 'Include Headers',
        'export.fileName': 'File Name',
        'export.exporting': 'Exporting...',
        'export.success': 'Export completed successfully!',
        'export.failed': 'Export failed: {error}',
        'export.downloadStarted': 'Download started...',
        'export.noData': 'No data to export',

        // Common table/filter terms - NEW TRANSLATIONS
        'common.clickToView': 'Click to view',
        'common.filterApplied': 'Filter applied',
        'common.searchApplied': 'Search applied',
        'common.loadingPermissions': 'Loading permissions...',
        'common.permissionDenied': 'Permission denied',
        'common.error': 'Error',
        'common.noDataFound': 'No data found',
        'common.selectAll': 'Select All',
        'common.assignTo': 'Assign to',
        'common.removeFrom': 'Remove from',
        'common.unlimited': 'Unlimited',
        'common.notAvailable': 'N/A',

        // General
        'general.loading': 'Loading...',
        'general.save': 'Save',
        'general.cancel': 'Cancel',
        'general.edit': 'Edit',
        'general.delete': 'Delete',
        'general.view': 'View',
        'general.close': 'Close',
        'general.yes': 'Yes',
        'general.no': 'No',
        'general.confirm': 'Confirm',
        'general.search': 'Search',

        // Language selector
        'language.english': 'English',
        'language.hebrew': 'עברית',
        'language.selectLanguage': 'Select Language',

        // Login translations
        'login.appTitle': 'Paragrutarally WebApp',
        'login.title': 'Login',
        'login.email': 'Email',
        'login.password': 'Password',
        'login.emailPlaceholder': 'Enter your email',
        'login.passwordPlaceholder': 'Enter your password',
        'login.show': 'Show',
        'login.hide': 'Hide',
        'login.signIn': 'Sign In',
        'login.signingIn': 'Signing In...',
        'login.forgotPassword': 'Forgot Password?',
        'login.mobileSignIn': 'Sign In With Mobile Number',
        'login.googleSignIn': 'Sign In With Google',
        'login.contactUs': 'Contact Us',
        'login.error': 'Failed to sign in. Please check your credentials.',

        // Status badges
        'status.active': 'Active',
        'status.pending': 'Pending',
        'status.completed': 'Completed',
        'status.cancelled': 'Cancelled',

        // Edit Kid Page
        'editKid.title': 'Update {firstName}\'s Info!',
        'editKid.titleGeneric': 'Update Racer\'s Info!',
        'editKid.backToProfile': 'Back to Profile',
        'editKid.loadingRacerData': 'Loading racer data...',
        'editKid.error': 'Error',
        'editKid.backToKids': 'Back to Kids',
        'editKid.editingInfo': 'You\'re editing {firstName}\'s information. Make changes below to update! 🏎️',
        'editKid.editingInfoGeneric': 'You\'re editing this racer\'s information. Make changes below to update! 🏎️',
        'editKid.kidNotFound': 'Kid not found!',
        'editKid.noPermission': 'You do not have permission to edit this kid.',
        'editKid.loadError': 'Failed to load kid data. Please try again.',
        'editKid.updateSuccess': '🎉 {firstName} has been updated successfully! 🏎️',
        'editKid.updateSuccessGeneric': '🎉 Racer has been updated successfully! 🏎️',
        'editKid.updateError': 'Failed to update kid: {error}',
        'editKid.photoUploadError': 'Photo upload failed: {error}. The kid will be updated without the new photo.',
        'editKid.vehicleAssignmentError': 'Failed to update vehicle assignment. Please try again.',
        'editKid.photoError': 'Failed to remove photo. Please try again.',
        'editKid.commentError': 'Failed to add comment. Please try again.',
        'editKid.focusIndicator': '← Update Here!',
        'editKid.racerProfile': '🏎️ Racer Profile',
        'editKid.superPowersSkills': '💪 Super Powers & Skills',
        'editKid.racingFamilyInfo': '👨‍👩‍👧‍👦 Racing Family Info',
        'editKid.teamVehicleAssignment': '🏎️ Team & Vehicle Assignment',
        'editKid.racingStatusForms': '📋 Racing Status & Forms',
        'editKid.racingNotesCommunication': '💬 Racing Notes & Team Communication',
        'editKid.racingPhoto': '📸 Racing Photo',
        'editKid.changePhoto': 'Change',
        'editKid.uploadPhoto': 'Upload',
        'editKid.removePhoto': 'Remove',
        'editKid.photoRequirements': '📸 Update racing photo! (Max 5MB, JPEG/PNG)',
        'editKid.photoUploadError.invalidType': 'Please upload a JPEG, PNG, or WebP image file.',
        'editKid.photoUploadError.tooLarge': 'Photo file size must be less than 5MB.',
        'editKid.photoUploadError.processingFailed': 'Failed to process photo. Please try again.',
        'editKid.raceNumber': '🏁 Race Number',
        'editKid.raceNumberPlaceholder': '001',
        'editKid.firstName': '👤 First Name',
        'editKid.firstNamePlaceholder': 'Future champion\'s first name',
        'editKid.lastName': '👨‍👩‍👧‍👦 Last Name',
        'editKid.lastNamePlaceholder': 'Racing family name',
        'editKid.birthday': '🎂 Birthday',
        'editKid.homeBaseLocation': '🏠 Home Base Location',
        'editKid.homeBaseLocationPlaceholder': 'Where our racer calls home',
        'editKid.amazingAbilities': '🌟 Amazing Abilities',
        'editKid.amazingAbilitiesPlaceholder': 'Tell us about this racer\'s awesome skills and abilities!',
        'editKid.announcerNotes': '📢 Announcer\'s Special Notes',
        'editKid.announcerNotesPlaceholder': 'Fun facts to share during the race!',
        'editKid.parentGuardianName': '👤 Parent/Guardian Name',
        'editKid.emailAddress': '📧 Email Address',
        'editKid.phoneNumber': '📱 Phone Number',
        'editKid.grandparentsNames': '👵👴 Grandparents Names',
        'editKid.grandparentsNamesPlaceholder': 'Racing legends in the family',
        'editKid.grandparentsPhone': '☎️ Grandparents Phone',
        'editKid.grandparentsPhonePlaceholder': 'Backup racing support',
        'editKid.racingTeam': 'Racing Team',
        'editKid.noTeamAssigned': '🚫 No Team Assigned (Yet!)',
        'editKid.teamOption': '🏁 {teamName} ({memberCount} racers)',
        'editKid.racingInstructor': 'Racing Instructor',
        'editKid.noInstructorAssigned': '👨‍🏫 No Instructor Assigned',
        'editKid.instructorOption': '🏎️ {instructorName}',
        'editKid.racingVehicleAssignment': 'Racing Vehicle Assignment',
        'editKid.assignedVehicle': 'Assigned Vehicle',
        'editKid.noVehicleAssigned': '🚫 No Vehicle Assigned',
        'editKid.vehicleOption': '🏎️ {make} {model} ({licensePlate})',
        'editKid.currentAssignment': 'Current Assignment:',
        'editKid.viewVehicleDetails': 'View Vehicle Details',
        'editKid.formStatus': 'Form Status',
        'editKid.healthDeclarationSigned': '🛡️ Health Declaration Signed',
        'editKid.noTeamNotesYet': 'No team notes yet. Be the first to add one!',
        'editKid.addTeamNote': 'Add Team Note',
        'editKid.commentPlaceholder': 'Add a note about this racer\'s progress, behavior, or any important information...',
        'editKid.cancel': 'Cancel',
        'editKid.addNote': 'Add Note',
        'editKid.adding': 'Adding...',
        'editKid.additionalRacingNotes': '🗒️ Additional Racing Notes',
        'editKid.additionalRacingNotesPlaceholder': 'Any special notes about our racing star!',
        'editKid.cancelButton': 'Cancel',
        'editKid.saveUpdates': 'Save Updates! 🏁',
        'editKid.uploadingPhoto': 'Uploading Photo...',
        'editKid.updatingRacer': 'Updating Racer...',
        'editKid.required': '*',
        'editKid.requiredField': '* Required field',
        'editKid.validation.fixErrors': 'Please fix the following errors:',
        'editKid.lockedField': 'This field cannot be edited',

        // View Kid Page
        'viewKid.racingStarProfile': 'Racing Star Profile!',
        'viewKid.meetOurRacer': 'Meet our amazing racer! 🏁',
        'viewKid.loadingRacingStarData': 'Loading racing star data...',
        'viewKid.kidNotFound': 'Kid not found!',
        'viewKid.noPermissionView': 'You do not have permission to view this kid.',
        'viewKid.loadDataError': 'Failed to load kid data. Please try again.',
        'viewKid.deleteConfirm': 'Are you sure you want to delete {kidName}? This action cannot be undone.',
        'viewKid.deleteSuccess': '{kidName} has been removed from the racing program.',
        'viewKid.deleteFailed': 'Failed to delete kid. Please try again.',
        'viewKid.deletePermissionDenied': 'You do not have permission to delete this kid.',
        'viewKid.nameRestricted': 'Name Restricted',
        'viewKid.kidNumber': 'Kid #{number}',
        'viewKid.ageLabel': 'Age: {age}',
        'viewKid.teamLabel': 'Team: {teamName}',
        'viewKid.vehicleLabel': 'Vehicle: {make} {model}',
        'viewKid.personalProfile': '🏎️ {firstName}\'s Profile',
        'viewKid.racingPhoto': '📸 Racing Photo',
        'viewKid.photoUploaded': '✅ Uploaded',
        'viewKid.noPhotoUploaded': '📷 No photo uploaded',
        'viewKid.homeBase': '🏠 Home Base',
        'viewKid.superPowersAbilities': '🌟 Super Powers & Abilities',
        'viewKid.announcerNotes': '📢 Announcer Notes',
        'viewKid.familyInfo': '👨‍👩‍👧‍👦 {firstName}\'s Family',
        'viewKid.parentGuardian': '👤 Parent/Guardian',
        'viewKid.email': '📧 Email',
        'viewKid.phone': '📱 Phone',
        'viewKid.grandparents': '👵👴 Grandparents',
        'viewKid.grandparentsPhone': '☎️ Grandparents Phone',
        'viewKid.teamVehicleInfo': '🏎️ {firstName}\'s Team & Vehicle',
        'viewKid.team': '🏁 Team',
        'viewKid.noTeamAssigned': 'No Team Assigned',
        'viewKid.formStatus': '📋 Form Status',
        'viewKid.safetyDeclaration': '🛡️ Safety Declaration',
        'viewKid.signed': '✅ Signed',
        'viewKid.pending': '⏳ Pending',
        'viewKid.racingVehicleAssignment': 'Racing Vehicle Assignment',
        'viewKid.noVehicleAssigned': 'No Vehicle Assigned',
        'viewKid.readyForAssignment': 'Ready for assignment!',
        'viewKid.licensePlate': 'License Plate:',
        'viewKid.type': 'Type:',
        'viewKid.battery': 'Battery:',
        'viewKid.status': 'Status:',
        'viewKid.vehicleActive': '✅ Active',
        'viewKid.vehicleInactive': '❌ Inactive',
        'viewKid.viewVehicle': 'View Vehicle',
        'viewKid.notesComments': '💬 {firstName}\'s Notes & Comments',
        'viewKid.parentComments': '👨‍👩‍👧‍👦 Parent Comments',
        'viewKid.organizationComments': '🏢 Organization Comments',
        'viewKid.teamLeaderComments': '👨‍🏫 Team Leader Comments',
        'viewKid.additionalNotes': '🗒️ Additional Notes',
        'viewKid.teamNotesHistory': '👨‍🏫 Team Notes History',
        'viewKid.noComments': 'No comments',
        'viewKid.noAdditionalNotes': 'No additional notes',
    },
    he: {
        // Navigation
        'nav.dashboard': 'לוח בקרה',
        'nav.eventManagement': 'ניהול אירועים',
        'nav.userManagement': 'ניהול משתמשים',
        'nav.forms': 'טפסים',
        'nav.backupSync': 'גיבוי וסנכרון',
        'nav.importExport': 'ייבוא וייצוא נתונים',
        'nav.gallery': 'גלריה',
        'nav.myAccount': 'החשבון שלי',
        'nav.signOut': 'התנתק',
        'nav.logo': 'פראגרוטרלי',
        'nav.events': 'אירועים',
        'nav.users': 'משתמשים',
        'nav.kids': 'ילדים',
        'nav.teams': 'קבוצות',
        'nav.vehicles': 'רכבים',

        // Dashboard
        'dashboard.title': 'לוח בקרה ראשי',
        'dashboard.totalUsers': 'סך המשתמשים',
        'dashboard.upcomingEvents': 'אירועים קרובים',
        'dashboard.totalKids': 'סך הילדים',
        'dashboard.activeTeams': 'קבוצות פעילות',
        'dashboard.recentActivities': 'פעילויות אחרונות',
        'dashboard.newUser': 'משתמש חדש',
        'dashboard.wasAdded': 'נוסף',
        'dashboard.event': 'אירוע',
        'dashboard.wasCreated': 'נוצר',
        'dashboard.newPhotos': 'תמונות חדשות',
        'dashboard.wereAdded': 'נוספו לגלריה',
        'dashboard.racingReady': 'מוכנים למירוץ',
        'dashboard.racingVehicles': 'רכבי מירוץ',
        'dashboard.available': 'זמינים',
        'dashboard.systemUsers': 'משתמשי מערכת',
        'dashboard.autoRefresh': 'הלוח מתעדכן אוטומטית כל 5 דקות',
        'dashboard.teamCreated': 'קבוצה <strong>{teamName}</strong> נוצרה.',
        'dashboard.justNow': 'עכשיו',
        'dashboard.minutesAgo': 'לפני {count} דקות',
        'dashboard.hoursAgo': 'לפני {count} שעות',
        'dashboard.daysAgo': 'לפני {count} ימים',

        // Event Management
        'events.title': 'ניהול אירועים',
        'events.createNew': 'צור אירוע חדש',
        'events.searchPlaceholder': 'חפש אירועים...',
        'events.search': 'חפש',
        'events.allEvents': 'כל האירועים',
        'events.upcoming': 'אירועים קרובים',
        'events.completed': 'אירועים שהסתיימו',
        'events.allLocations': 'כל המיקומים',
        'events.jerusalem': 'ירושלים',
        'events.telAviv': 'תל אביב',
        'events.haifa': 'חיפה',
        'events.eilat': 'אילת',
        'events.date': 'תאריך',
        'events.location': 'מיקום',
        'events.participants': 'משתתפים',
        'events.status': 'סטטוס',
        'events.actions': 'פעולות',
        'events.edit': 'ערוך',
        'events.view': 'צפה',
        'events.delete': 'מחק',
        'events.loading': 'טוען אירועים...',
        'events.noEvents': 'לא נמצאו אירועים',
        'events.previous': 'הקודם',
        'events.next': 'הבא',
        'events.addNewEvent': 'הוסף אירוע חדש',
        'events.exportEvents': 'ייצא אירועים',
        'events.totalEvents': 'סך האירועים',
        'events.completedEvents': 'אירועים שהושלמו',
        'events.eventInfo': 'מידע אירוע',
        'events.eventsLowercase': 'אירועים',
        'events.showing': 'מציג',
        'events.searchLabel': 'חיפוש',
        'events.unnamedEvent': 'אירוע ללא שם',
        'events.noDescription': 'אין תיאור זמין',
        'events.locationTBD': 'מיקום יקבע',
        'events.dateTBD': 'תאריך יקבע',
        'events.fetchError': 'כשל בטעינת אירועים. אנא נסה שוב.',
        'events.noGalleryFolder': 'לאירוע זה אין תיקיית גלריה.',
        'events.deleteSuccess': 'אירוע "{eventName}" נמחק בהצלחה',
        'events.includingGallery': 'כולל תמונות גלריה',
        'events.deleteFailed': 'מחיקת אירוע נכשלה: {error}',
        'events.deleteError': 'מחיקת אירוע נכשלה. אנא נסה שוב.',
        'events.noEventsCreated': 'עדיין לא נוצרו אירועים. התחל ביצירת האירוע הראשון שלך!',
        'events.createFirstEvent': 'צור אירוע ראשון',
        'events.createNewEvent': 'צור אירוע חדש',
        'events.hasGallery': 'יש גלריה',
        'events.viewDetails': 'צפה בפרטים',
        'events.editEvent': 'ערוך אירוע',
        'events.viewGallery': 'צפה בגלריה',
        'events.deleteEvent': 'מחק אירוע',
        'events.description': 'תיאור',
        'events.notes': 'הערות',
        'events.participatingTeams': 'קבוצות משתתפות',
        'events.teamsRegistered': '{count} קבוצות רשומות',
        'events.gallery': 'גלריה',
        'events.deleteConfirmTitle': 'האם אתה בטוח שברצונך למחוק את האירוע הזה?',
        'events.deleteConfirmMessage': 'אתה עומד למחוק את "{eventName}". פעולה זו בלתי הפיכה.',
        'events.deletionSummaryTitle': 'הדברים הבאים יימחקו לצמיתות:',
        'events.eventInformation': 'מידע האירוע והפרטים',
        'events.eventCoverImage': 'תמונת כיסוי האירוע',
        'events.allGalleryPhotos': 'כל התמונות בגלריית האירוע',
        'events.galleryFolderDetected': 'תיקיית גלריה זוהתה',
        'events.galleryFolderQuestion': 'לאירוע זה יש גלריית תמונות קשורה. מה תרצה לעשות עם התמונות?',
        'events.keepGalleryPhotos': 'שמור תמונות גלריה',
        'events.keepGalleryDescription': 'מחק רק את האירוע, שמר את כל התמונות בגלריה',
        'events.deleteGalleryToo': 'מחק גם את הגלריה',
        'events.deleteGalleryDescription': 'מחק את האירוע והסר לצמיתות את כל התמונות מהגלריה',
        'events.deleting': 'מוחק...',
        'events.deleteEventAndGallery': 'מחק אירוע וגלריה',
        'events.deleteEventOnly': 'מחק אירוע בלבד',
        'events.upcomingEvents': 'אירועים קרובים',
        'events.timeTBD': 'שעה תקבע בהמשך',
        'events.addressTBD': 'כתובת תקבע בהמשך',
        'events.organizerTBD': 'יקבע',
        'events.eventNotFound': 'אירוע לא נמצא',
        'events.loadError': 'כשל בטעינת אירוע. אנא נסה שוב.',
        'events.loadingEvent': 'טוען אירוע...',
        'events.backToEvents': 'חזור לאירועים',
        'events.racingEventDetails': 'פרטי אירוע מירוץ!',
        'events.eventInformationSubtitle': 'מידע ופרטי האירוע',
        'events.eventDetails': 'פרטי האירוע',
        'events.time': 'שעה',
        'events.organizer': 'מארגן',
        'events.fullAddress': 'כתובת מלאה',
        'events.additionalNotes': 'הערות נוספות',
        'events.loadingTeamData': 'טוען נתוני קבוצות...',
        'events.unknownTeam': 'קבוצה לא ידועה',
        'events.leader': 'מנהיג',
        'events.kidsInTeam': 'ילדים בקבוצה',
        'events.eventGallery': 'גלריית האירוע',
        'events.eventAlbum': 'אלבום {eventName}',
        'events.viewManagePhotos': 'צפה ונהל תמונות מהאירוע הזה',
        'events.cancelled': 'בוטל',
        'events.editRacingEvent': 'ערוך אירוע מירוץ',
        'events.loadingEventData': 'טוען נתוני אירוע...',
        'events.racingEvent': 'אירוע מירוץ',
        'events.racingEventDescription': 'אירוע מירוץ תחרותי עם זוכים',
        'events.newFamiliesEvent': 'אירוע משפחות חדשות',
        'events.newFamiliesEventDescription': 'קבלת פנים למשפחות חדשות עם יום מירוץ כיפי',
        'events.socialEvent': 'אירוע חברתי',
        'events.socialEventDescription': 'התכנסות קהילתית ופעילויות',
        'events.basicInformation': 'מידע בסיסי',
        'events.eventName': 'שם האירוע',
        'events.eventNamePlaceholder': 'לדוגמה, אליפות מירוץ הקיץ 2025',
        'events.requiredField': '*שדה חובה',
        'events.eventType': 'סוג האירוע',
        'events.descriptionPlaceholder': 'תאר את אירוע המירוץ שלך בפירוט...',
        'events.organizerPlaceholder': 'שם מארגן האירוע',
        'events.dateAndTime': 'תאריך ושעה',
        'events.eventDate': 'תאריך האירוע',
        'events.eventTime': 'שעת האירוע',
        'events.futureDateTime': '*תאריך ושעת האירוע חייבים להיות בעתיד',
        'events.locationDetails': 'פרטי מיקום',
        'events.locationName': 'שם המיקום',
        'events.locationPlaceholder': 'לדוגמה, פארק מירוצים ירושלים',
        'events.addressPlaceholder': 'כתובת מלאה של האירוע',
        'events.teamsAssigned': '{count} קבוצות מוקצות',
        'events.addTeams': 'הוסף קבוצות',
        'events.removeTeam': 'הסר קבוצה',
        'events.noTeamsAssigned': 'עדיין לא הוקצו קבוצות לאירוע זה.',
        'events.addTeamsHint': 'לחץ על "הוסף קבוצות" כדי להקצות קבוצות להשתתפות.',
        'events.eventImage': 'תמונת האירוע',
        'events.eventImageOptional': 'תמונת האירוע (אופציונלי)',
        'events.clickToUpload': 'לחץ להעלאת תמונת אירוע',
        'events.imageRecommendation': 'מומלץ: 1200x600px, JPG או PNG',
        'events.cancelNewImage': 'בטל תמונה חדשה',
        'events.clickToChange': 'לחץ לשינוי תמונה',
        'events.additionalDetails': 'פרטים נוספים',
        'events.notesOptional': 'הערות (אופציונלי)',
        'events.notesPlaceholder': 'הערות נוספות על האירוע...',
        'events.updateEvent': 'עדכן אירוע',
        'events.uploadingImage': 'מעלה תמונה...',
        'events.updatingEvent': 'מעדכן אירוע...',
        'events.imageUploadWarning': 'אזהרה: העלאת תמונה חדשה נכשלה, אך האירוע יתעדכן עם השינויים האחרים.',
        'events.additionalNotesDefault': 'הערות נוספות על האירוע',
        'events.updateSuccess': 'האירוע עודכן בהצלחה!',
        'events.updateError': 'שגיאה בעדכון אירוע: {error}',


        // User Management
        'users.title': 'ניהול משתמשים',
        'users.manage': 'נהל משתמשים',
        'users.description': 'עמוד זה יכיל פונקציונליות ניהול משתמשים כולל:',
        'users.viewAll': 'צפה בכל המשתמשים',
        'users.addNew': 'הוסף משתמשים חדשים',
        'users.editProfiles': 'ערוך פרופילי משתמשים',
        'users.manageRoles': 'נהל תפקידי משתמשים',
        'users.permissions': 'הרשאות משתמשים',
        'users.addNewUser': 'הוסף משתמש חדש',
        'users.exportUsers': 'ייצא משתמשים',
        'users.createNewUser': 'צור משתמש חדש',
        'users.totalUsers': 'סך המשתמשים',
        'users.admins': 'מנהלים',
        'users.instructors': 'מדריכים',
        'users.parents': 'הורים',
        'users.admin': 'מנהל',
        'users.instructor': 'מדריך',
        'users.parent': 'הורה',
        'users.host': 'מארח',
        'users.searchPlaceholder': 'חפש משתמשים לפי שם או אימייל...',
        'users.filterByRole': 'סנן לפי תפקיד',
        'users.allRoles': 'כל התפקידים',
        'users.clearFilters': 'נקה מסננים',
        'users.showing': 'מציג',
        'users.usersLowercase': 'משתמשים',
        'users.filteredBy': 'מסונן לפי',
        'users.searching': 'מחפש',
        'users.loadingUsers': 'טוען משתמשים...',
        'users.noUsersFound': 'לא נמצאו משתמשים',
        'users.createFirstUser': 'התחל ביצירת המשתמש הראשון שלך.',
        'users.searchInUsers': 'חפש במשתמשים',
        'users.clearSearch': 'נקה חיפוש',
        'users.searchResults': '{count} מתוך {total} משתמשים',
        'users.totalUsersCount': '{count} משתמשים בסך הכל',
        'users.sortByDisplayName': 'לחץ למיון לפי שם תצוגה',
        'users.sortByFullName': 'לחץ למיון לפי שם מלא',
        'users.sortByEmail': 'לחץ למיון לפי אימייל',
        'users.sortByPhone': 'לחץ למיון לפי טלפון',
        'users.sortByRole': 'לחץ למיון לפי תפקיד',
        'users.sortByCreatedDate': 'לחץ למיון לפי תאריך יצירה',
        'users.sortByLastLogin': 'לחץ למיון לפי כניסה אחרונה',
        'users.displayName': 'שם תצוגה',
        'users.fullName': 'שם מלא',
        'users.email': 'אימייל',
        'users.phone': 'טלפון',
        'users.role': 'תפקיד',
        'users.createdAt': 'נוצר ב',
        'users.lastLogin': 'כניסה אחרונה',
        'users.actions': 'פעולות',
        'users.updateUser': 'עדכן משתמש',
        'users.update': 'עדכן',
        'users.noSearchResults': 'אין משתמשים התואמים לחיפוש שלך: "{searchTerm}"',
        'users.clearSearchButton': 'נקה חיפוש',
        'users.editUser': 'ערוך משתמש',
        'users.displayNameRequired': 'שם תצוגה הוא שדה חובה',
        'users.nameRequired': 'שם הוא שדה חובה',
        'users.phoneRequired': 'מספר טלפון הוא שדה חובה',
        'users.roleRequired': 'תפקיד הוא שדה חובה',
        'users.updateError': 'עדכון המשתמש נכשל. אנא נסה שוב.',
        'users.displayNamePlaceholder': 'הכנס שם תצוגה',
        'users.emailAddress': 'כתובת אימייל',
        'users.emailCannotChange': 'לא ניתן לשנות אימייל',
        'users.emailLinkedToAuth': 'לא ניתן לשנות אימייל מכיוון שהוא מקושר לאימות',
        'users.fullNamePlaceholder': 'הכנס שם מלא',
        'users.phoneNumber': 'מספר טלפון',
        'users.phoneNumberPlaceholder': 'הכנס מספר טלפון',
        'users.updating': 'מעדכן...',
        'users.updateUserButton': 'עדכן משתמש',

        // My Account
        'account.title': 'החשבון שלי',
        'account.profile': 'מידע אישי',
        'account.security': 'הגדרות אבטחה',
        'account.preferences': 'העדפות',
        'account.editProfile': 'ערוך פרופיל',
        'account.fullName': 'שם מלא',
        'account.email': 'כתובת אימייל',
        'account.phone': 'מספר טלפון',
        'account.organization': 'ארגון',
        'account.bio': 'ביוגרפיה',
        'account.saveChanges': 'שמור שינויים',
        'account.cancel': 'בטל',

        // Forms
        'forms.title': 'ניהול טפסים',
        'forms.manage': 'נהל טפסים',
        'forms.description': 'עמוד זה יכיל פונקציונליות ניהול טפסים כולל:',
        'forms.createNew': 'צור טפסים חדשים',
        'forms.editExisting': 'ערוך טפסים קיימים',
        'forms.viewSubmissions': 'צפה בהגשות טפסים',
        'forms.templates': 'תבניות טפסים',
        'forms.analytics': 'ניתוח טפסים',
        'forms.createNewForm': 'צור טופס חדש',
        'forms.viewTemplates': 'צפה בתבניות',

        // Backup/Sync
        'backup.title': 'גיבוי וסנכרון',
        'backup.databaseBackup': 'גיבוי מסד נתונים',
        'backup.description': 'צור ונהל גיבויים של נתוני האפליקציה שלך.',
        'backup.createNew': 'צור גיבוי חדש',
        'backup.viewHistory': 'צפה בהיסטוריית גיבויים',
        'backup.recentBackups': 'גיבויים אחרונים',
        'backup.noBackups': 'עדיין לא נוצרו גיבויים. לחץ על "צור גיבוי חדש" כדי להתחיל.',
        'backup.cloudSync': 'הגדרות סנכרון ענן',
        'backup.configurSync': 'הגדר סנכרון עם שירותי אחסון בענן.',
        'backup.googleDrive': 'גוגל דרייב',
        'backup.dropbox': 'דרופבוקס',
        'backup.status': 'סטטוס',
        'backup.notConnected': 'לא מחובר',
        'backup.connect': 'התחבר',
        'backup.automatedSchedule': 'לוח זמנים אוטומטי לגיבוי',
        'backup.setSchedule': 'הגדר גיבויים אוטומטיים על בסיס קבוע.',
        'backup.daily': 'יומי',
        'backup.weekly': 'שבועי',
        'backup.monthly': 'חודשי',
        'backup.custom': 'מותאם אישית',
        'backup.saveSettings': 'שמור הגדרות',

        // Import/Export
        'import.title': 'ייבוא וייצוא נתונים',
        'import.importData': 'ייבוא נתונים',
        'import.importDescription': 'העלה קבצי נתונים כדי לייבא מידע למערכת.',
        'import.selectDataType': 'בחר סוג נתונים לייבוא:',
        'import.selectFile': 'בחר קובץ (CSV או Excel):',
        'import.users': 'משתמשים',
        'import.kids': 'ילדים',
        'import.teams': 'קבוצות',
        'import.events': 'אירועים',
        'import.selectedFile': 'קובץ נבחר:',
        'import.size': 'גודל:',
        'import.overwriteRecords': 'דרוס רשומות קיימות',
        'import.skipHeader': 'דלג על שורת כותרת',
        'import.importButton': 'ייבא נתונים',
        'import.exportData': 'ייצוא נתונים',
        'import.exportDescription': 'הורד נתונים מהמערכת כקבצי CSV או Excel.',
        'import.selectExportType': 'בחר סוג נתונים לייצוא:',
        'import.allData': 'כל הנתונים',
        'import.exportFormat': 'פורמט ייצוא:',
        'import.csv': 'CSV',
        'import.excel': 'Excel',
        'import.includeHeaders': 'כלול שורת כותרת',
        'import.includeTimestamp': 'כלול חותמת זמן בשם הקובץ',
        'import.exportButton': 'ייצא נתונים',
        'import.recentActivity': 'פעילות אחרונה',

        // Gallery
        'gallery.title': 'גלריה',
        'gallery.allPhotos': 'כל התמונות',
        'gallery.events': 'אירועים',
        'gallery.races': 'מרוצים',
        'gallery.teams': 'קבוצות',
        'gallery.awards': 'טקסי הוקרה',
        'gallery.uploadPhotos': 'העלה תמונות',
        'gallery.noPhotos': 'לא נמצאו תמונות באלבום זה.',

        // Teams Management (Hebrew) - NEW TRANSLATIONS
        'teams.title': 'ניהול קבוצות',
        'teams.addNewTeam': 'הוסף קבוצה חדשה',
        'teams.refresh': 'רענן',
        'teams.exportTeams': 'ייצא קבוצות',
        'teams.totalTeams': 'סך הקבוצות',
        'teams.activeTeams': 'קבוצות פעילות',
        'teams.teamsWithoutKids': 'קבוצות ללא ילדים',
        'teams.teamsWithKids': 'קבוצות עם ילדים',
        'teams.searchPlaceholder': 'חפש לפי שם קבוצה או מדריך...',
        'teams.clearAll': 'נקה הכל',
        'teams.showing': 'מציג',
        'teams.of': 'מתוך',
        'teams.teams': 'קבוצות',
        'teams.priorityFilter': 'עדיפות: קבוצות ללא ילדים',
        'teams.status': 'סטטוס',
        'teams.capacity': 'קיבולת',
        'teams.allStatus': 'כל הסטטוסים',
        'teams.active': 'פעיל',
        'teams.inactive': 'לא פעיל',
        'teams.allTeams': 'כל הקבוצות',
        'teams.emptyTeams': 'קבוצות ריקות',
        'teams.availableSpots': 'מקומות פנויים',
        'teams.fullTeams': 'קבוצות מלאות',
        'teams.teamInfo': 'מידע קבוצה',
        'teams.instructor': 'מדריך',
        'teams.members': 'חברים',
        'teams.actions': 'פעולות',
        'teams.noInstructor': 'אין מדריך',
        'teams.loadingTeams': 'טוען קבוצות...',
        'teams.noTeamsFound': 'לא נמצאו קבוצות',
        'teams.adjustFilters': 'נסה להתאים את החיפוש או הפילטרים',
        'teams.addFirstTeam': 'הוסף קבוצה ראשונה',
        'teams.reset': 'איפוס',
        'teams.permissionError': 'שגיאת הרשאה',
        'teams.reloadPage': 'טען מחדש',
        'teams.tryAgain': 'נסה שוב',
        'teams.deleteConfirm': 'האם אתה בטוח שברצונך למחוק את {teamName}? פעולה זו בלתי הפיכה.',
        'teams.cannotDelete': 'לא ניתן למחוק את {teamName} כי יש לה {memberCount} חברים. אנא העבר את הילדים לקבוצות אחרות תחילה.',
        'teams.deleteSuccess': '{teamName} נמחקה בהצלחה!',
        'teams.deleteFailed': 'מחיקת הקבוצה נכשלה. אנא נסה שוב.',
        'teams.onlyAdminsCanDelete': 'רק מנהלים יכולים למחוק קבוצות.',
        'teams.unnamedTeam': 'קבוצה ללא שם',
        'teams.loadError': 'כשל בטעינת קבוצות',
        'teams.editFunctionality': 'פונקציונליות עריכה עבור {teamName} תהיה כאן.',
        'teams.viewDetails': 'צפה בפרטים',
        'teams.editTeam': 'ערוך קבוצה',
        'teams.deleteTeam': 'מחק קבוצה',
        'teams.unlimited': 'ללא הגבלה',
        'teams.hasInstructor': 'יש מדריך',
        'teams.membersCount': '{current}/{max}',
        'teams.empty': 'ריק',
        'teams.available': 'זמין',
        'teams.full': 'מלא',
        'teams.updateRacingTeam': 'עדכן קבוצת מירוצים!',
        'teams.loadingTeamData': 'טוען נתוני קבוצה...',
        'teams.teamNotFound': 'קבוצה לא נמצאה!',
        'teams.loadDataError': 'כשל בטעינת נתוני הקבוצה. אנא נסה שוב.',
        'teams.updateSuccess': '🏁 קבוצה "{teamName}" עודכנה בהצלחה! 🏎️',
        'teams.updateError': 'כשל בעדכון הקבוצה. אנא נסה שוב.',
        'teams.viewingCurrentInfo': 'אתה צופה במידע הנוכחי של קבוצה {teamName}. בצע שינויים למטה כדי לעדכן! 🏎️',
        'teams.backToTeams': 'חזור לקבוצות',
        'teams.teamIdentity': '🏎️ זהות הקבוצה',
        'teams.racingInstructors': '👨‍🏫 מדריכי מירוצים',
        'teams.teamRacers': '🏎️ רוכבי הקבוצה ({current}/{max})',
        'teams.teamNotes': '📝 הערות קבוצה',
        'teams.teamName': 'שם הקבוצה',
        'teams.teamNamePlaceholder': 'רוכבי הרעם, שדי המהירות, ברקי הזעם...',
        'teams.maxRacers': 'מספר רוכבים מקסימלי',
        'teams.teamDescription': 'תיאור הקבוצה',
        'teams.teamDescriptionPlaceholder': 'מה עושה את הקבוצה הזו מיוחדת? רוח המירוצים, עבודת הצוות או כישורים מיוחדים...',
        'teams.teamStatus': 'סטטוס הקבוצה',
        'teams.activeReady': '✅ פעילה ומוכנה למירוץ',
        'teams.inactivePrep': '⏸️ לא פעילה (מצב הכנה)',
        'teams.focusIndicator': '← עדכן כאן!',
        'teams.noInstructorsAvailable': 'אין מדריכים זמינים. הוסף כמה מדריכים תחילה!',
        'teams.teamLeader': 'מנהיג הקבוצה',
        'teams.chooseTeamLeader': '🎯 בחר מנהיג קבוצה',
        'teams.leaderOption': '👑 {instructorName}',
        'teams.capacityWarning': 'אזהרת קיבולת',
        'teams.noKidsAvailable': 'אין ילדים זמינים להקצאה! 🎉',
        'teams.allKidsAssigned': 'כל הילדים כבר מוקצים לקבוצות.',
        'teams.currentlyInOtherTeam': '📍 כרגע בקבוצה אחרת',
        'teams.nameRequired': 'שם הקבוצה הוא שדה חובה',
        'teams.capacityRange': 'קיבולת מקסימלית חייבת להיות בין 1 ל-50',
        'teams.tooManyKids': 'לא ניתן להקצות יותר ילדים ({current}) מהקיבולת המקסימלית ({max})',
        'teams.specialNotesStrategy': '📝 הערות מיוחדות ואסטרטגיה',
        'teams.notesPlaceholder': 'אסטרטגיית הקבוצה, דרישות מיוחדות או כל הערות חשובות אחרות...',
        'teams.updatingTeam': 'מעדכן קבוצה...',
        'teams.saveUpdates': 'שמור עדכונים! 🏁',
        'teams.noChangesToSave': 'אין שינויים לשמירה',

       // Kids Management Page (Hebrew)
        'kids.title': 'ניהול ילדים',
        'kids.addNewKid': 'הוסף ילד חדש',
        'kids.refresh': 'רענן',
        'kids.exportKids': 'ייצא ילדים',
        'kids.kidsWithoutTeams': 'ילדים ללא קבוצות',
        'kids.totalKids': 'סך הילדים',
        'kids.yourKids': 'הילדים שלך',
        'kids.activeKids': 'ילדים פעילים',
        'kids.kidsWithTeams': 'ילדים עם קבוצות',
        'kids.searchPlaceholder': 'חפש לפי שם ילד או הורה...',
        'kids.clearAll': 'נקה הכל',
        'kids.showing': 'מציג',
        'kids.of': 'מתוך',
        'kids.kids': 'ילדים',
        'kids.priorityFilter': 'עדיפות: ילדים ללא קבוצות',
        'kids.teamStatus': 'סטטוס קבוצה',
        'kids.allKids': 'כל הילדים',
        'kids.noTeam': 'ללא קבוצה',
        'kids.withTeam': 'עם קבוצה',
        'kids.allStatus': 'כל הסטטוסים',
        'kids.pending': 'ממתין',
        'kids.completed': 'הושלם',
        'kids.cancelled': 'בוטל',
        'kids.active': 'פעיל',
        'kids.kidInfo': 'מידע ילד',
        'kids.photo': 'תמונה',
        'kids.age': 'גיל',
        'kids.team': 'קבוצה',
        'kids.status': 'סטטוס',
        'kids.actions': 'פעולות',
        'kids.loadingKids': 'טוען ילדים...',
        'kids.noKidsFound': 'לא נמצאו ילדים',
        'kids.noKidsRegistered': 'אין ילדים רשומים תחת החשבון שלך',
        'kids.adjustFilters': 'נסה להתאים את החיפוש או הפילטרים',
        'kids.addFirstKid': 'הוסף ילד ראשון',
        'kids.assignTeam': 'הקצה קבוצה',
        'kids.changeTeam': 'שנה קבוצה',
        'kids.deleteConfirm': 'האם אתה בטוח שברצונך למחוק את {kidName}? פעולה זו בלתי הפיכה.',
        'kids.deleteSuccess': '{kidName} נמחק בהצלחה!',
        'kids.deleteFailed': 'מחיקת הילד נכשלה. אנא נסה שוב.',
        'kids.onlyAdminsCanDelete': 'רק מנהלים יכולים למחוק ילדים.',
        'kids.teamChanged': '{kidName} {action} {teamName}',
        'kids.assignedTo': 'הוקצה ל',
        'kids.removedFrom': 'הוסר מהקבוצה',
        'kids.updated': '{kidName} עודכן בהצלחה!',
        'kids.name': 'שם',
        'kids.parentName': 'הורה',
        'kids.participantNumber': 'מספר משתתף',
        'kids.viewDetails': 'צפה בפרטים',
        'kids.editKid': 'ערוך ילד',
        'kids.deleteKid': 'מחק ילד',
        'kids.clickToView': 'לחץ לצפייה בפרטים',
        'kids.reset': 'איפוס',
        'kids.permissionError': 'שגיאת הרשאה',
        'kids.reloadPage': 'טען מחדש',
        'kids.tryAgain': 'נסה שוב',
        'kids.loadingPermissions': 'טוען הרשאות...',

        // Status badges (Hebrew)
        'status.active': 'פעיל',
        'status.pending': 'ממתין',
        'status.completed': 'הושלם',
        'status.cancelled': 'בוטל',

        // Export functionality (Hebrew) - NEW TRANSLATIONS
        'export.title': 'ייצוא נתונים',
        'export.description': 'הורד נתונים כקבצי Excel או CSV',
        'export.selectFormat': 'בחר פורמט',
        'export.excel': 'Excel (XLSX)',
        'export.csv': 'CSV',
        'export.includeHeaders': 'כלול כותרות',
        'export.fileName': 'שם קובץ',
        'export.exporting': 'מייצא...',
        'export.success': 'הייצוא הושלם בהצלחה!',
        'export.failed': 'הייצוא נכשל: {error}',
        'export.downloadStarted': 'ההורדה החלה...',
        'export.noData': 'אין נתונים לייצוא',

        // Common table/filter terms (Hebrew) - NEW TRANSLATIONS
        'common.clickToView': 'לחץ לצפייה',
        'common.filterApplied': 'פילטר מופעל',
        'common.searchApplied': 'חיפוש מופעל',
        'common.loadingPermissions': 'טוען הרשאות...',
        'common.permissionDenied': 'הרשאה נדחתה',
        'common.error': 'שגיאה',
        'common.noDataFound': 'לא נמצאו נתונים',
        'common.selectAll': 'בחר הכל',
        'common.assignTo': 'הקצה ל',
        'common.removeFrom': 'הסר מ',
        'common.unlimited': 'ללא הגבלה',
        'common.notAvailable': 'לא זמין',

        // General
        'general.loading': 'טוען...',
        'general.save': 'שמור',
        'general.cancel': 'בטל',
        'general.edit': 'ערוך',
        'general.delete': 'מחק',
        'general.view': 'צפה',
        'general.close': 'סגור',
        'general.yes': 'כן',
        'general.no': 'לא',
        'general.confirm': 'אשר',
        'general.search': 'חפש',

        // Language selector
        'language.english': 'English',
        'language.hebrew': 'עברית',
        'language.selectLanguage': 'בחר שפה',

        // Hebrew login translations
        'login.appTitle': 'אפליקציית פראגרוטרלי',
        'login.title': 'התחברות',
        'login.email': 'אימייל',
        'login.password': 'סיסמה',
        'login.emailPlaceholder': 'הכנס את האימייל שלך',
        'login.passwordPlaceholder': 'הכנס את הסיסמה שלך',
        'login.show': 'הצג',
        'login.hide': 'הסתר',
        'login.signIn': 'התחבר',
        'login.signingIn': 'מתחבר...',
        'login.forgotPassword': 'שכחת סיסמה?',
        'login.mobileSignIn': 'התחבר עם מספר נייד',
        'login.googleSignIn': 'התחבר עם גוגל',
        'login.contactUs': 'צור קשר',
        'login.error': 'כשל בהתחברות. אנא בדוק את פרטי ההתחברות שלך.',

         // Edit Kid Page (Hebrew)
        'editKid.title': 'עדכן את המידע של {firstName}!',
        'editKid.titleGeneric': 'עדכן מידע של הרוכב!',
        'editKid.backToProfile': 'חזור לפרופיל',
        'editKid.loadingRacerData': 'טוען נתוני רוכב...',
        'editKid.error': 'שגיאה',
        'editKid.backToKids': 'חזור לילדים',
        'editKid.editingInfo': 'אתה עורך את המידע של {firstName}. בצע שינויים למטה כדי לעדכן! 🏎️',
        'editKid.editingInfoGeneric': 'אתה עורך את המידע של הרוכב הזה. בצע שינויים למטה כדי לעדכן! 🏎️',
        'editKid.kidNotFound': 'ילד לא נמצא!',
        'editKid.noPermission': 'אין לך הרשאה לערוך את הילד הזה.',
        'editKid.loadError': 'כשל בטעינת נתוני הילד. אנא נסה שוב.',
        'editKid.updateSuccess': '🎉 {firstName} עודכן בהצלחה! 🏎️',
        'editKid.updateSuccessGeneric': '🎉 הרוכב עודכן בהצלחה! 🏎️',
        'editKid.updateError': 'כשל בעדכון הילד: {error}',
        'editKid.photoUploadError': 'העלאת תמונה נכשלה: {error}. הילד יתעדכן ללא התמונה החדשה.',
        'editKid.vehicleAssignmentError': 'כשל בעדכון הקצאת הרכב. אנא נסה שוב.',
        'editKid.photoError': 'כשל בהסרת התמונה. אנא נסה שוב.',
        'editKid.commentError': 'כשל בהוספת הערה. אנא נסה שוב.',
        'editKid.focusIndicator': '← עדכן כאן!',
        'editKid.racerProfile': '🏎️ פרופיל רוכב',
        'editKid.superPowersSkills': '💪 כוחות על וכישורים',
        'editKid.racingFamilyInfo': '👨‍👩‍👧‍👦 מידע משפחת מירוצים',
        'editKid.teamVehicleAssignment': '🏎️ הקצאת קבוצה ורכב',
        'editKid.racingStatusForms': '📋 סטטוס מירוצים וטפסים',
        'editKid.racingNotesCommunication': '💬 הערות מירוצים ותקשורת צוות',
        'editKid.racingPhoto': '📸 תמונת מירוצים',
        'editKid.changePhoto': 'שנה',
        'editKid.uploadPhoto': 'העלה',
        'editKid.removePhoto': 'הסר',
        'editKid.photoRequirements': '📸 עדכן תמונת מירוצים! (מקסימום 5MB, JPEG/PNG)',
        'editKid.photoUploadError.invalidType': 'אנא העלה קובץ תמונה JPEG, PNG או WebP.',
        'editKid.photoUploadError.tooLarge': 'גודל קובץ התמונה חייב להיות פחות מ-5MB.',
        'editKid.photoUploadError.processingFailed': 'כשל בעיבוד התמונה. אנא נסה שוב.',
        'editKid.raceNumber': '🏁 מספר מירוץ',
        'editKid.raceNumberPlaceholder': '001',
        'editKid.firstName': '👤 שם פרטי',
        'editKid.firstNamePlaceholder': 'שם פרטי של אלוף העתיד',
        'editKid.lastName': '👨‍👩‍👧‍👦 שם משפחה',
        'editKid.lastNamePlaceholder': 'שם משפחת מירוצים',
        'editKid.birthday': '🎂 יום הולדת',
        'editKid.homeBaseLocation': '🏠 מיקום בית',
        'editKid.homeBaseLocationPlaceholder': 'איפה הרוכב שלנו קורא לבית',
        'editKid.amazingAbilities': '🌟 יכולות מדהימות',
        'editKid.amazingAbilitiesPlaceholder': 'ספר לנו על הכישורים והיכולות המדהימות של הרוכב הזה!',
        'editKid.announcerNotes': '📢 הערות מיוחדות לקריין',
        'editKid.announcerNotesPlaceholder': 'עובדות כיפיות לחלוק במהלך המירוץ!',
        'editKid.parentGuardianName': '👤 שם הורה/אפוטרופוס',
        'editKid.emailAddress': '📧 כתובת אימייל',
        'editKid.phoneNumber': '📱 מספר טלפון',
        'editKid.grandparentsNames': '👵👴 שמות סבא וסבתא',
        'editKid.grandparentsNamesPlaceholder': 'אגדות מירוצים במשפחה',
        'editKid.grandparentsPhone': '☎️ טלפון סבא וסבתא',
        'editKid.grandparentsPhonePlaceholder': 'גיבוי תמיכת מירוצים',
        'editKid.racingTeam': 'קבוצת מירוצים',
        'editKid.noTeamAssigned': '🚫 אין קבוצה מוקצית (עדיין!)',
        'editKid.teamOption': '🏁 {teamName} ({memberCount} רוכבים)',
        'editKid.racingInstructor': 'מדריך מירוצים',
        'editKid.noInstructorAssigned': '👨‍🏫 אין מדריך מוקצה',
        'editKid.instructorOption': '🏎️ {instructorName}',
        'editKid.racingVehicleAssignment': 'הקצאת רכב מירוצים',
        'editKid.assignedVehicle': 'רכב מוקצה',
        'editKid.noVehicleAssigned': '🚫 אין רכב מוקצה',
        'editKid.vehicleOption': '🏎️ {make} {model} ({licensePlate})',
        'editKid.currentAssignment': 'הקצאה נוכחית:',
        'editKid.viewVehicleDetails': 'צפה בפרטי הרכב',
        'editKid.formStatus': 'סטטוס טופס',
        'editKid.healthDeclarationSigned': '🛡️ הצהרת בריאות חתומה',
        'editKid.noTeamNotesYet': 'עדיין אין הערות צוות. היה הראשון להוסיף!',
        'editKid.addTeamNote': 'הוסף הערת צוות',
        'editKid.commentPlaceholder': 'הוסף הערה על התקדמות הרוכב, התנהגות או כל מידע חשוב...',
        'editKid.cancel': 'בטל',
        'editKid.addNote': 'הוסף הערה',
        'editKid.adding': 'מוסיף...',
        'editKid.additionalRacingNotes': '🗒️ הערות מירוצים נוספות',
        'editKid.additionalRacingNotesPlaceholder': 'כל הערות מיוחדות על כוכב המירוצים שלנו!',
        'editKid.cancelButton': 'בטל',
        'editKid.saveUpdates': 'שמור עדכונים! 🏁',
        'editKid.uploadingPhoto': 'מעלה תמונה...',
        'editKid.updatingRacer': 'מעדכן רוכב...',
        'editKid.required': '*',
        'editKid.requiredField': '* שדה חובה',
        'editKid.validation.fixErrors': 'אנא תקן את השגיאות הבאות:',
        'editKid.lockedField': 'לא ניתן לערוך שדה זה',

         // View Kid Page
        'viewKid.racingStarProfile': 'פרופיל כוכב מירוצים!',
        'viewKid.meetOurRacer': 'היכרו עם הרוכב המדהים שלנו! 🏁',
        'viewKid.loadingRacingStarData': 'טוען נתוני כוכב מירוצים...',
        'viewKid.kidNotFound': 'ילד לא נמצא!',
        'viewKid.noPermissionView': 'אין לך הרשאה לצפות בילד הזה.',
        'viewKid.loadDataError': 'כשל בטעינת נתוני הילד. אנא נסה שוב.',
        'viewKid.deleteConfirm': 'האם אתה בטוח שברצונך למחוק את {kidName}? פעולה זו בלתי הפיכה.',
        'viewKid.deleteSuccess': '{kidName} הוסר מתוכנית המירוצים.',
        'viewKid.deleteFailed': 'מחיקת הילד נכשלה. אנא נסה שוב.',
        'viewKid.deletePermissionDenied': 'אין לך הרשאה למחוק את הילד הזה.',
        'viewKid.nameRestricted': 'שם מוגבל',
        'viewKid.kidNumber': 'ילד מס\' {number}',
        'viewKid.ageLabel': 'גיל: {age}',
        'viewKid.teamLabel': 'קבוצה: {teamName}',
        'viewKid.vehicleLabel': 'רכב: {make} {model}',
        'viewKid.personalProfile': '🏎️ הפרופיל של {firstName}',
        'viewKid.racingPhoto': '📸 תמונת מירוצים',
        'viewKid.photoUploaded': '✅ הועלה',
        'viewKid.noPhotoUploaded': '📷 לא הועלתה תמונה',
        'viewKid.homeBase': '🏠 בית',
        'viewKid.superPowersAbilities': '🌟 כוחות על ויכולות',
        'viewKid.announcerNotes': '📢 הערות קריין',
        'viewKid.familyInfo': '👨‍👩‍👧‍👦 המשפחה של {firstName}',
        'viewKid.parentGuardian': '👤 הורה/אפוטרופוס',
        'viewKid.email': '📧 אימייל',
        'viewKid.phone': '📱 טלפון',
        'viewKid.grandparents': '👵👴 סבא וסבתא',
        'viewKid.grandparentsPhone': '☎️ טלפון סבא וסבתא',
        'viewKid.teamVehicleInfo': '🏎️ הקבוצה והרכב של {firstName}',
        'viewKid.team': '🏁 קבוצה',
        'viewKid.noTeamAssigned': 'אין קבוצה מוקצית',
        'viewKid.formStatus': '📋 סטטוס טופס',
        'viewKid.safetyDeclaration': '🛡️ הצהרת בטיחות',
        'viewKid.signed': '✅ חתום',
        'viewKid.pending': '⏳ ממתין',
        'viewKid.racingVehicleAssignment': 'הקצאת רכב מירוצים',
        'viewKid.noVehicleAssigned': 'אין רכב מוקצה',
        'viewKid.readyForAssignment': 'מוכן להקצאה!',
        'viewKid.licensePlate': 'לוחית רישוי:',
        'viewKid.type': 'סוג:',
        'viewKid.battery': 'סוללה:',
        'viewKid.status': 'סטטוס:',
        'viewKid.vehicleActive': '✅ פעיל',
        'viewKid.vehicleInactive': '❌ לא פעיל',
        'viewKid.viewVehicle': 'צפה ברכב',
        'viewKid.notesComments': '💬 הערות והתבוננויות של {firstName}',
        'viewKid.parentComments': '👨‍👩‍👧‍👦 הערות הורים',
        'viewKid.organizationComments': '🏢 הערות ארגון',
        'viewKid.teamLeaderComments': '👨‍🏫 הערות מנהיג קבוצה',
        'viewKid.additionalNotes': '🗒️ הערות נוספות',
        'viewKid.teamNotesHistory': '👨‍🏫 היסטוריית הערות צוות',
        'viewKid.noComments': 'אין הערות',
        'viewKid.noAdditionalNotes': 'אין הערות נוספות',
    }
};

// Create the context
const LanguageContext = createContext();

// Custom hook to use the language context
export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

// Language provider component
export const LanguageProvider = ({ children }) => {
    // Get initial language from localStorage or default to English
    const getInitialLanguage = () => {
        if (typeof window !== 'undefined') {
            const savedLanguage = localStorage.getItem('charity-app-language');
            if (savedLanguage && Object.values(LANGUAGES).includes(savedLanguage)) {
                return savedLanguage;
            }
        }
        return LANGUAGES.ENGLISH;
    };

    const [currentLanguage, setCurrentLanguage] = useState(getInitialLanguage);

    // Function to apply an RTL/LTR direction to a document
    const applyDirection = (language) => {
        if (typeof document !== 'undefined') {
            const isRTL = language === LANGUAGES.HEBREW;
            document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
            document.documentElement.lang = language;

            // Add/remove RTL class to the body for additional styling
            if (isRTL) {
                document.body.classList.add('rtl');
                document.body.classList.remove('ltr');
            } else {
                document.body.classList.add('ltr');
                document.body.classList.remove('rtl');
            }
        }
    };

    // Effect to handle language changes
    useEffect(() => {
        // Apply direction
        applyDirection(currentLanguage);

        // Save language preference to localStorage
        if (typeof window !== 'undefined') {
            localStorage.setItem('charity-app-language', currentLanguage);
        }
    }, [currentLanguage]);

    // Function to change language
    const changeLanguage = (newLanguage) => {
        if (Object.values(LANGUAGES).includes(newLanguage)) {
            setCurrentLanguage(newLanguage);
        }
    };

    // Function to get translation with interpolation support
    const t = (key, defaultValue = '', interpolations = {}) => {
        const translation = translations[currentLanguage]?.[key] || defaultValue || key;

        // Handle interpolations like {teamName}, {kidName}, etc.
        if (interpolations && Object.keys(interpolations).length > 0) {
            return translation.replace(/{(\w+)}/g, (match, placeholder) => {
                return interpolations[placeholder] || match;
            });
        }

        return translation;
    };

    // Computed values
    const isRTL = currentLanguage === LANGUAGES.HEBREW;
    const isHebrew = currentLanguage === LANGUAGES.HEBREW;
    const isEnglish = currentLanguage === LANGUAGES.ENGLISH;

    // Context value
    const value = {
        // Current state
        currentLanguage,
        isRTL,
        isHebrew,
        isEnglish,

        // Functions
        changeLanguage,
        t,

        // Constants
        LANGUAGES
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};

export default LanguageContext;